name: Unit testing
on: [push]
jobs:
  unit-testing:
    runs-on: ubuntu-latest
    container: node:14-alpine
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: cd app && yarn

      - name: Tests Suites
        run: cd app && yarn run test:unit
